function [g3]=kernel_gauss3D(xx,yy,zz,x0,y0,z0,sx,sy,sz)

    g3=1/((2*pi)^(3/2)*sx*sy*sz).*...
                                 exp(-0.5*((xx-x0)/sx).^2).*...
                                 exp(-0.5*((yy-y0)/sy).^2).*...
                                 exp(-0.5*((zz-z0)/sz).^2);

end